version: 2.1

jobs:
  build-and-test:
    parallelism: 2
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            pip install pytest
      - run:
          name: Run tests
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)
            echo $TEST_FILES
            mkdir -p target
            python -m pytest --verbose --junitxml=target/junit-something.xml $TEST_FILES
      - store_test_results:
          path: target
      - store_artifacts:
          path: target
workflows:
  sample:
    jobs:
      - build-and-test