version: 2.1

jobs:
  install:
    working_directory: /tmp/workspace/repo
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - persist_to_workspace:
          root:
            /tmp/workspace
          paths:
            - repo

  build-and-test:
    working_directory: /tmp/workspace/repo
    parallelism: 2
    docker:
      - image: cimg/python:3.11
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install deps
          command: |
            pip install pytest
      - run:
          name: test detection
          command: |
            circleci tests glob "tests/**/test_*.py"
      - run:
          name: Run tests
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --verbose --split-by=timings)
            echo $TEST_FILES
            mkdir -p target
            python -m pytest --verbose -o junit_family=legacy --junitxml=target/reportses/test-junit-something-report.xml $TEST_FILES
      - store_test_results:
          path: target/reportses/
      - store_artifacts:
          path: target/reportses/
      - persist_to_workspace:
          root:
            /tmp/workspace
          paths:
            - repo/target/reportses/

  endresult:
    working_directory: /tmp/workspace/repo
    docker:
      - image: cimg/python:3.11
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run tests
          command: |
            ls target/reports

workflows:
  sample:
    jobs:
      - install
      - build-and-test:
          requires:
            - install
      - endresult:
          requires:
            - build-and-test